# Generated by Django 4.2 on 2023-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_searchquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquery',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='query',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='query_text',
            field=models.CharField(default='default value', max_length=255),
        ),
    ]
